### ISSUE TITLE
Build failed on GCC 7.0

### ISSUE THREAD

**Issue by Hubbitus** [Hubbitus/rpm-rigsofrods#1]
```
CMakeFiles/RoRConfig.dir/conf_file.cpp.o: In function `Settings::getUTFSetting(Ogre::UTFString, Ogre::UTFString)':
/builddir/build/BUILD/rigs-of-rods-0.4.7.0/source/configurator/conf_file.cpp:97: undefined reference to `Ogre::UTFString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
CMakeFiles/RoRConfig.dir/conf_file.cpp.o: In function `Settings::getUTFSetting(Ogre::UTFString, Ogre::UTFString)':
conf_file.cpp:(.text+0xb17): undefined reference to `Ogre::UTFString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
CMakeFiles/RoRConfig.dir/conf_file.cpp.o: In function `Settings::setUTFSetting(Ogre::UTFString, Ogre::UTFString)':
conf_file.cpp:(.text+0x1003): undefined reference to `Ogre::UTFString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
conf_file.cpp:(.text+0x1010): undefined reference to `Ogre::UTFString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
collect2: error: ld returned 1 exit status
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/1336/17521336/build.log

**Comment by Hubbitus** [comment]
It looks it build fine on GCC 7.1 - https://koji.fedoraproject.org/koji/taskinfo?taskID=22792831. So closing.
